<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_68a837bcde3c7',
    'title' => __('Exhibition', 'api-exhibition-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_68ac02c9b0b86',
            'label' => __('General', 'api-exhibition-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
            'selected' => 0,
        ),
        1 => array(
            'key' => 'field_68ac1ad88307d',
            'label' => __('Organizer', 'api-exhibition-manager'),
            'name' => 'organizer',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Dunkers Kulturhus' => __('Dunkers Kulturhus', 'api-exhibition-manager'),
                'Helsingborgs Muséum' => __('Helsingborgs Muséum', 'api-exhibition-manager'),
                'Helsingborgs Konsthall' => __('Helsingborgs Konsthall', 'api-exhibition-manager'),
            ),
            'default_value' => __('Dunkers Kulturhus', 'api-exhibition-manager'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        2 => array(
            'key' => 'field_68ac00ccb5b3e',
            'label' => __('Start date', 'api-exhibition-manager'),
            'name' => 'startDate',
            'aria-label' => '',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'Y-m-d',
            'return_format' => 'Y-m-d',
            'first_day' => 1,
        ),
        3 => array(
            'key' => 'field_68ac0124b5b3f',
            'label' => __('End date', 'api-exhibition-manager'),
            'name' => 'endDate',
            'aria-label' => '',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'Y-m-d',
            'return_format' => 'Y-m-d',
            'first_day' => 1,
        ),
        4 => array(
            'key' => 'field_68ac003ab5b3c',
            'label' => __('Description', 'api-exhibition-manager'),
            'name' => 'description',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        5 => array(
            'key' => 'field_68ac004fb5b3d',
            'label' => __('Images', 'api-exhibition-manager'),
            'name' => 'image',
            'aria-label' => '',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'insert' => 'append',
            'preview_size' => 'medium',
        ),
        6 => array(
            'key' => 'field_68ac0bd3f4645',
            'label' => __('Opening hours', 'api-exhibition-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
            'selected' => 0,
        ),
        7 => array(
            'key' => 'field_68ac0c15245c6',
            'label' => __('Opening hours', 'api-exhibition-manager'),
            'name' => 'openingHoursSpecification',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till rad', 'api-exhibition-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_68ac0cd0245c7',
                    'label' => __('Day(s)', 'api-exhibition-manager'),
                    'name' => 'days',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '70',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'monday' => __('Monday', 'api-exhibition-manager'),
                        'tuesday' => __('Tuesday', 'api-exhibition-manager'),
                        'wednesday' => __('Wednesday', 'api-exhibition-manager'),
                        'thursday' => __('Thursday', 'api-exhibition-manager'),
                        'friday' => __('Friday', 'api-exhibition-manager'),
                        'saturday' => __('Saturday', 'api-exhibition-manager'),
                        'sunday' => __('Sunday', 'api-exhibition-manager'),
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'multiple' => 1,
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_68ac0c15245c6',
                ),
                1 => array(
                    'key' => 'field_68ac0d44993ef',
                    'label' => __('Open', 'api-exhibition-manager'),
                    'name' => 'open',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui_on_text' => __('Öppet', 'api-exhibition-manager'),
                    'ui_off_text' => __('Stängt', 'api-exhibition-manager'),
                    'ui' => 1,
                    'parent_repeater' => 'field_68ac0c15245c6',
                ),
                2 => array(
                    'key' => 'field_68ac0d5d993f0',
                    'label' => __('Opens', 'api-exhibition-manager'),
                    'name' => 'opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68ac0d44993ef',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                    'parent_repeater' => 'field_68ac0c15245c6',
                ),
                3 => array(
                    'key' => 'field_68ac0dec993f1',
                    'label' => __('Closes', 'api-exhibition-manager'),
                    'name' => 'closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68ac0d44993ef',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                    'parent_repeater' => 'field_68ac0c15245c6',
                ),
            ),
        ),
        8 => array(
            'key' => 'field_68ac0327da3e3',
            'label' => __('Location', 'api-exhibition-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
            'selected' => 0,
        ),
        9 => array(
            'key' => 'field_68ac0190886cb',
            'label' => __('Location name', 'api-exhibition-manager'),
            'name' => 'locationname',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        10 => array(
            'key' => 'field_68ac0141886ca',
            'label' => __('Address', 'api-exhibition-manager'),
            'name' => 'location',
            'aria-label' => '',
            'type' => 'google_map',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => '56.04673',
            'center_lng' => '12.69437',
            'zoom' => '',
            'height' => '',
        ),
        11 => array(
            'key' => 'field_68ac13cd996cd',
            'label' => __('Offers', 'api-exhibition-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        12 => array(
            'key' => 'field_68ac13e8996ce',
            'label' => __('Offers', 'api-exhibition-manager'),
            'name' => 'offers',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till rad', 'api-exhibition-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_68ac1421996cf',
                    'label' => __('Label', 'api-exhibition-manager'),
                    'name' => 'name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_68ac13e8996ce',
                ),
                1 => array(
                    'key' => 'field_68ac144a996d1',
                    'label' => __('Free', 'api-exhibition-manager'),
                    'name' => 'free',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui_on_text' => __('Yes', 'api-exhibition-manager'),
                    'ui_off_text' => __('No', 'api-exhibition-manager'),
                    'ui' => 1,
                    'parent_repeater' => 'field_68ac13e8996ce',
                ),
                2 => array(
                    'key' => 'field_68ac142c996d0',
                    'label' => __('Amount', 'api-exhibition-manager'),
                    'name' => 'amount',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68ac144a996d1',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'api-exhibition-manager'),
                    'parent_repeater' => 'field_68ac13e8996ce',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'exhibition',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'discussion',
        4 => 'comments',
        5 => 'slug',
        6 => 'format',
        7 => 'page_attributes',
        8 => 'featured_image',
        9 => 'categories',
        10 => 'tags',
        11 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 1,
));
}